version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.2-fpm-alpine
    volumes:
      - ./src:/var/www/html
    environment:
      CHANNELS_DVR_IP: ${CHANNELS_DVR_IP}